### ISSUE TITLE
Getting an API key

### ISSUE THREAD

**Issue by fferegrino** [KennyRich/GraphRAG#1]
1. Go to this website: https://london2024.pydata.org/cfp/login/
2. Once you are registered and logged in, go to this other website: https://london2024.pydata.org/orga/me
3. Scroll to the bottom
4. Success!

**Comment by fferegrino** [comment]
Probably good to add it in a readme.md file

**Comment by KennyRich** [comment]
> Probably good to add it in a readme.md file

Thank you! I've added it
